# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.3
    hooks:
        # Run the linter.
        - id: ruff
          args: [--fix, --select, I]
        # Run the formatter.
        - id: ruff-format

-   repo: local
    hooks:
      - id: commie-review
        name: Commit Review
        entry: rye run commit-review
        language: python
        types: [python]
        pass_filenames: false
        verbose: true